[timeleapcam]
wifi_ssid = "<Your AP SSID>"
wifi_psk = "<Your AP Password>"
http_server = ""
resolution = "8"
track_id = "0"
timezone_offset = "9"
auto_capture = "false"
idle_in_sleep_time = "300"
duration = "0"
api_key = "<API KEY for openAI>"
model = "gpt-4o"
query_openai = "false"
query_prompt = "If heavy rain is expected in 30 minutes, please include a 'NOTICE' with the reason in your reply. If not, simply respond with 'NONE'. Heavy rain is defined as 30mm/h or more."
post_account = "<Your LINE Account ID>"
post_access_token = "<Access Token for LINE Message>"
storage_account = "<Your Cloudflare Account ID>"
storage_access_token = "<Your Cloudflare Access Token>"
storage_signed_key = "<Your Cloudflare Image Signed Key>"
post_message_trigger = "NOTICE"
autofocus_once = "true"
status_report = "false"
status_report_interval = "10"
post_interval = "3600"
leap_day = "-1"
leap_hour = "-1"
leap_minute = "-1"