[timeleapcam]
wifi_ssid = "<Your AP SSID>"
wifi_psk = "<Your AP Password>"
http_server = ""
resolution = "8"
track_id = "0"
timezone_offset = "9"
auto_capture = "false"
idle_in_sleep_time = "300"
duration = "0"
api_key = "<API KEY for openAI>"
model = "gpt-4o"
query_openai = "false"
query_prompt = "If is there somebody, Add in the reply as 'NOTICE' and reason. If is nobody, Just reply is 'NONE'."
post_account = "<Your LINE Account ID>"
post_access_token = "<Access Token for LINE Message>"
storage_account = "<Your Cloudflare Account ID>"
storage_access_token = "Your Cloudflare Access Token>"
post_message_trigger = "NOTICE"